import {useQuery} from '@tanstack/react-query';
import {api,type ScannerRow} from '../../services/api';
import {OpportunityTable} from './OpportunityTable';
import {useWorkspace} from '../../workspace/store';
export function ScannerPage(){
 const s=useWorkspace(),f=s.scannerFilters;const set=(key:string,value:string|boolean)=>s.set({scannerFilters:{...f,[key]:value}});
 const params=new URLSearchParams({limit:'1000',q:f.q,review_state:f.review,classification:f.classification,quantity:f.quantity||'10',max_age:f.maxAge||'45',min_capacity:f.minCapacity||'0'});if(f.minNet)params.set('min_net_edge',f.minNet);
 const result=useQuery({queryKey:['scanner',params.toString()],queryFn:()=>api<{items:ScannerRow[];total:number}>('/opportunities?'+params),refetchInterval:15000});
 const rows=(result.data?.items??[]).filter(r=>(!f.verified||r.verified)&&(!f.expiry||!!r.expiry&&r.expiry.slice(0,10)<=f.expiry));
 return <div className="page"><div className="page-heading"><div className="eyebrow">SCAN / OPPORTUNITIES</div><h1>Cross-venue candidate scanner</h1><p>Eligibility gates remain visible. Only reviewed equivalent mappings with valid books and known fees can enter the verified subset.</p></div><div className="filterbar"><label>Topic / outcome<input value={f.q} onChange={e=>set('q',e.target.value)} placeholder="Filter candidates"/></label><label>Match class<select value={f.classification} onChange={e=>set('classification',e.target.value)}><option value="">All classes</option>{['EXACT','SYNTHETIC_EQUIVALENT','RELATED','REJECTED'].map(v=><option key={v}>{v}</option>)}</select></label><label>Review state<select value={f.review} onChange={e=>set('review',e.target.value)}><option value="">All reviews</option>{['UNREVIEWED','APPROVED','REVOKED'].map(v=><option key={v}>{v}</option>)}</select></label>{([['quantity','Size (units)'],['minCapacity','Min capacity'],['minNet','Min net floor ($)'],['maxAge','Max age (s)']] as const).map(([key,label])=><label key={key}>{label}<input type="number" min={key==='quantity'||key==='maxAge'?1:0} value={f[key]} onChange={e=>set(key,e.target.value)}/></label>)}<label>Expiry by<input type="date" value={f.expiry} onChange={e=>set('expiry',e.target.value)}/></label><label className="check"><input type="checkbox" checked={f.verified} onChange={e=>set('verified',e.target.checked)}/> Verified only</label><button onClick={()=>result.refetch()}>Refresh</button></div>{result.error&&<p className="error">{result.error.message}</p>}<OpportunityTable rows={rows}/>{!rows.length&&<p className="empty">{result.isPending?'Loading…':'No candidates meet these filters. Import events or inspect the unverified subset.'}</p>}<p className="footnote">{rows.length} rows · Virtualized · Unknown fees or lot sizes block verified signals.</p></div>;
}
